[tool.poetry]
name = "ipres-package-cloud"
version = "0.1.0"
description = ""
authors = ["Nick Krabbenhoeft <nickkrabbenhoeft@nypl.org>"]
readme = "README.md"
packages = [{include = "ipres_package_cloud", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
bagit = "^1.8.1"

[tool.poetry.scripts]
package_cloud = 'ipres_package_cloud.package_cloud:main'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
